name: publish

on: 
 push:
  branches:
  - master

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/sudhirpandey/hello-world:latest
        docker run ghcr.io/sudhirpandey/hello-world:latest
        docker push ghcr.io/sudhirpandey/hello-world:latest
